{"timestamp":"2025-09-23T17:11:22.849210","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-09-23T17:11:22.849722","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/evaluate_and_promote_to_staging_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-09-23T17:11:27.210297Z","level":"info","event":"Staging 후보 평가 프로세스를 시작합니다.","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T17:11:27.250635","level":"warning","event":"Retrying (Retry(total=6, connect=6, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76dedb700590>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=credit_fraud_experiment","logger":"urllib3.connectionpool"}
{"timestamp":"2025-09-23T17:11:31.600516","level":"warning","event":"Retrying (Retry(total=5, connect=5, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76dedb7007d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=credit_fraud_experiment","logger":"urllib3.connectionpool"}
{"timestamp":"2025-09-23T17:11:40.655746","level":"warning","event":"Retrying (Retry(total=4, connect=4, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76dedb7007a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=credit_fraud_experiment","logger":"urllib3.connectionpool"}
{"timestamp":"2025-09-23T17:11:56.807401","level":"warning","event":"Retrying (Retry(total=3, connect=3, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76dedb700950>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=credit_fraud_experiment","logger":"urllib3.connectionpool"}
